### ISSUE TITLE
Node loosing structure file

### ISSUE THREAD

**Issue by mapchen** [codmpm/node-red-contrib-loxone#45] opened 2020-02-12 22:44 UTC
I have updated node red to version 1.0.3 and loxone node to 0.10.5. by that I have lost connection in all loxone nodes. Tried to recreate the connection but it could not get the structure file. Only if I pull in a new node the structure file is received. When I deploy all nodes loose connection again.

![image](https://user-images.githubusercontent.com/56200461/74384258-2fa4ad80-4df1-11ea-85ee-e180ebb57b14.png)

when running node-red-log i receive following error when picking a miniserver node 

> TypeError: Cannot read property 'active' of null
    at /root/.node-red/node_modules/node-red-contrib-loxone/loxone/loxone.js:24:24
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)

>

**Comment by codmpm** [comment] 2020-02-13 12:05
Duplicate of #41

**Closed as completed by codmpm** 2020-02-13 12:05 UTC
